# Generated by Django 4.2 on 2023-05-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Task',
            new_name='task',
        ),
    ]
