# Generated by Django 4.2 on 2023-05-12 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_todo_assignee_alter_todo_assignor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assignee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='assignor',
            field=models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='managaer', to=settings.AUTH_USER_MODEL),
        ),
    ]
