# Generated by Django 4.2 on 2023-05-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Inprogress', 'INPROGRESS'), ('Submitted', 'SUBMITTED')], max_length=20),
        ),
    ]
