# Generated by Django 4.2 on 2023-05-12 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='todo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.todo'),
            preserve_default=False,
        ),
    ]
