# Generated by Django 4.2 on 2023-05-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_manager_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='todo',
        ),
        migrations.AddField(
            model_name='manager',
            name='todo',
            field=models.ManyToManyField(to='app.todo'),
        ),
    ]
