# Generated by Django 4.2 on 2023-05-12 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_manager_todo_manager_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.manager'),
            preserve_default=False,
        ),
    ]
