# Generated by Django 4.2 on 2023-05-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_todo_user_todo_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='manager',
        ),
    ]
